networks:
  mapnet:
    external: true
  
services:
  map-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: pwd
      DB_NAME: ros_db
      UDP_PORT: 9000
    ports:
      - "9000:9000"
    restart: on-failure
    command: ["./server_udp"]
    networks: [mapnet]
    
volumes:
  db_data: