FROM debian:bookworm-slim


RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libpqxx-dev \
    libpq-dev \
    libssl-dev \
    libboost-all-dev \
    libgtest-dev \
    gtest \
    libgtest-dev \
    libboost-test-dev \
    libboost-filesystem-dev \
    libboost-system-dev \
    libboost-thread-dev \
    libboost-program-options-dev \
    pkg-config \
    git \
    libxml2-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

    WORKDIR /usr/src/app

    COPY . .

    RUN mkdir build && cd build && cmake .. && make

    WORKDIR /usr/src/app/build
    CMD ["./server_udp", "--help"]